### ISSUE TITLE
Failed to activate the technobabble package

### ISSUE THREAD

**Issue by sfelch** [lawren/atom-technobabble#6]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Linux Mint
**Thrown From**: [technobabble](https://github.com/lawren/atom-technobabble) package, v0.3.3
### Stack Trace

Failed to activate the technobabble package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (/home/scott/.atom/packages/technobabble/lib/technobabble.coffee:51:23)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:232:19)
  at /usr/share/atom/resources/app.asar/src/package.js:212:32
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:153:15)
  at /usr/share/atom/resources/app.asar/src/package.js:205:26
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:201:34)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:474:21)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
  at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
  at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
  at /usr/share/atom/resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)

```
### Commands

```
     -0:14.4.0 settings-view:install-packages-and-themes (atom-pane.pane.active)
     -0:12.9.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:08.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:07.5.0 editor:move-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true
  }
}
```
### Installed Packages

``` coffee
# User
minimap, v4.15.0
technobabble, v0.3.3

# Dev
No dev packages
```

**Comment by Leeds-eBooks** [comment]
Any update on this issue? Still happening for me

**Comment by johnblommers** [comment]
Still broken here too.

**Comment by step21** [comment]
All text placeholder packages seem to be broken. :-/

**Comment by step21** [comment]
This is due to an api change, I got a fix locally, will make a pull request soon.

**Comment by dahoo** [comment]
@step21 Any update?

**Comment by step21** [comment]
https://github.com/lawren/atom-technobabble/pull/7 you can wait until it is merged or use my repo at step21/atom-technobabble - clone to .atom/packages/technobabble and reload the window or restart atom.

**Comment by lawren** [comment]
@step21 Sorry mate, I don't know how I didn't see this until over a year later. Better late then never I suppose. Merged and closed.

**Comment by johnblommers** [comment]
This is a welcome development because every time I startup Atom I get the problem message about Technobabble version 0.3.3 not starting up.

Can you set expectations about when users will likely find the new installer in Atom's installation menu?

**Comment by lawren** [comment]
@johnblommers I just updated the Atom package. Please let me know if that works for you.

**Comment by johnblommers** [comment]
Yes.  Technobabble version 0.4 now installs and operates as it should.  Many thanks.
